/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const PERSONAS = {
  cinema: {
    wes: { name: "Wes Anderson", prompt: "Director Persona: Wes Anderson. Style: Twee, Symmetrical, Pastel. Visuals: Obsessive symmetry, central composition, flat lighting, one-point perspective. Characters looking directly at camera. Color Palette: Pastel pink, baby blue, yellow, mint green. Aesthetic: Toy house, detailed props, whimsical, diorama-like. CRITICAL: Full screen image only." },
    tim: { name: "Tim Burton", prompt: "Director Persona: Tim Burton. Style: Gothic Fantasy, German Expressionism. Visuals: Long skinny figures, spiral patterns, crooked architecture, exaggerated makeup, dark fairytale atmosphere. Color Palette: High contrast black and white with splashes of gothic purple, dark blue, or blood red. Aesthetic: Eerie, whimsical, spooky. CRITICAL: Full screen image only." },
    kubrick: { name: "Stanley Kubrick", prompt: "Director Persona: Stanley Kubrick. Style: Cold Perfectionism, Psychological Horror/Sci-Fi. Visuals: One-point perspective, symmetrical corridors, 'The Kubrick Stare', wide angle lenses. Color Palette: Sterile white, cold blue, contrasted with alarming bright red. Aesthetic: Unsettling, hypnotic, clinical, precise. CRITICAL: Full screen image only." },
    tarantino: { name: "Quentin Tarantino", prompt: "Director Persona: Quentin Tarantino. Style: Stylized Violence, Neo-Noir, Pulp. Visuals: Low angle 'Trunk Shot', dynamic composition, grindhouse aesthetic. Color Palette: High saturation, vivid yellow and black (Kill Bill style), bright blood red. Aesthetic: Comic book vibrancy, cinematic cool, retro texture. CRITICAL: Full screen image only." },
    fincher: { name: "David Fincher", prompt: "Director Persona: David Fincher. Style: Dark Thriller, Neo-Noir. Visuals: Low-key lighting, heavy shadows, precise composition, silhouettes. Color Palette: Color graded with desaturated yellow, moss green, and amber tints. Avoid pure blues. Aesthetic: Gritty, realistic but stylized, psychological tension. CRITICAL: Full screen image only." }
  },
  anime: {
    miyazaki: { name: "Hayao Miyazaki (Ghibli)", prompt: "Director Persona: Hayao Miyazaki. Style: Studio Ghibli, Hand-drawn Masterpiece. Visuals: Studio Ghibli style. Characters with emotional hair movement. Color Palette: Vivid organic greens, deep sky blues, warm earthy tones. Rich oil-painting-like backgrounds. Aesthetic: Nostalgic, magical realism, nature worship." },
    shinkai: { name: "Makoto Shinkai", prompt: "Director Persona: Makoto Shinkai. Style: Modern Anime, The Magician of Light. Visuals: Excessive lens flares, photorealistic backgrounds (train stations, rain), glistening wet surfaces. Focus on light and shadow as emotional tools. Color Palette: Magic hour lighting (sunset gradients), deep purples, oranges, and blues. High saturation and glowing effects. Aesthetic: Melancholic romance, visual spectacle." },
    kon: { name: "Satoshi Kon", prompt: "Director Persona: Satoshi Kon. Style: Psychological Thriller, Surreal Anime. Visuals: Match cuts, merging reality with dreams, claustrophobic and detailed urban settings. Realistic but expressive character faces. Color Palette: Neon reds, dull greys of the city, clashing with bright, disturbing circus-like colors in dream sequences. Aesthetic: Mind-bending, chaotic, disorienting." },
    oshii: { name: "Mamoru Oshii", prompt: "Director Persona: Mamoru Oshii. Style: Cyberpunk, Philosophical Sci-Fi. Visuals: 'Pillow shots' (long, static shots of cityscapes), technical precision in machinery and weapons. Characters often still or slow-moving. Color Palette: Cold, metallic, sterile. Dominant pale green and steel blue filters (Ghost in the Shell style). Aesthetic: Intellectual, cold, digital loneliness." },
    anno: { name: "Hideaki Anno", prompt: "Director Persona: Hideaki Anno. Style: Deconstructive Anime, Psychological Drama. Visuals: Aggressive editing, fetishistic close-ups of industrial details (traffic lights, pylons). Static elevator scenes. Color Palette: High contrast, unsettling. Iconic Purple, Neon Green, and Orange combinations. Harsh black and white contrast. Aesthetic: Depressive, chaotic, mechanical." }
  },
  photo: {
    crewdson: { name: "Gregory Crewdson", prompt: "Photographer Persona: Gregory Crewdson. Style: Cinematic Stillness, Staged Photography. Visuals: American suburbia at twilight, mysterious beams of light from windows, frozen/alienated characters. Elaborate movie-set production values. Color Palette: Twilight blue ambient light contrasted with warm tungsten orange from windows. Aesthetic: Uncanny valley, psychological mystery, suspended narrative." },
    leiter: { name: "Saul Leiter", prompt: "Photographer Persona: Saul Leiter. Style: Abstract Street Photography, Impressionist. Visuals: Shooting through steamy windows, rain-spattered glass, or between objects. High use of negative space and bokeh/blur in foreground. Color Palette: Muted pastels interrupted by splashes of vibrant red, burgundy, or mustard yellow. Aesthetic: Painterly, voyeuristic, soft, nostalgic." },
    parr: { name: "Martin Parr", prompt: "Photographer Persona: Martin Parr. Style: Satirical Documentary, Kitsch. Visuals: Direct Ring Flash usage even in daylight, harsh shadows, extreme close-ups of food or people. Unflattering angles. Color Palette: Hyper-saturated, garish, 'cheap' feeling bright colors. Pop-art aesthetic. Aesthetic: Absurdist, humorous, critical of consumption, raw." },
    ho: { name: "Fan Ho", prompt: "Photographer Persona: Fan Ho. Style: Cinematic Black & White, Chiaroscuro. Visuals: Geometric composition, dramatic shafts of sunlight cutting through smoke/fog in urban alleys (Hong Kong). Silhouette figures. Color Palette: Black and White ONLY. High contrast: pitch black shadows and blinding white highlights. Aesthetic: Theatrical, atmospheric, geometric, nostalgic noir." },
    walker: { name: "Tim Walker", prompt: "Photographer Persona: Tim Walker. Style: Whimsical, Fairy Tale, Magical Realism. Visuals: Giant props (oversized cats, flowers), physical sets instead of CGI, dreamlike logic, ruined castles, people walking on clouds. Perspective and scale distortion. Color Palette: Soft, romantic, powdery pastels. Pale pink, baby blue, antique white, cream. Aesthetic: Hazy, theatrical, old dream, Alice in Wonderland vibe." }
  },
  oil: {
    vangogh: { name: "Vincent van Gogh", prompt: "Painter Persona: Vincent van Gogh. Style: Post-Impressionism, Impasto. Visuals: Thick, visible, swirling brushstrokes (starry night style). Rhythmic movement in the sky and trees. Black contours around objects. Color Palette: Complementary contrasts, specifically Yellow (Sunflower) and Cobalt Blue. Aesthetic: Emotional, turbulent, tactile texture." },
    rembrandt: { name: "Rembrandt van Rijn", prompt: "Painter Persona: Rembrandt. Style: Baroque, Tenebrism. Visuals: Dramatic Chiaroscuro (extreme light/dark contrast). Single light source illuminating the face, background fading into pitch black darkness. Realistic skin texture and melancholic expressions. Color Palette: Warm earthy tones: dark browns, golden ochre, deep reds, rich blacks. Aesthetic: Moody, soulful, expensive, classic." },
    monet: { name: "Claude Monet", prompt: "Painter Persona: Claude Monet. Style: Impressionism. Visuals: No sharp lines, focus on light qualities. Fleeting moments, dabs of paint, blurry and soft focus. Water lilies, gardens, reflections. Color Palette: Pastel, airy light colors. Lilac, seafoam green, pale blue, pink. Shadows are purple/blue, not black. Aesthetic: Atmospheric, vibrating light, peaceful, nature." },
    klimt: { name: "Gustav Klimt", prompt: "Painter Persona: Gustav Klimt. Style: Art Nouveau, Symbolism. Visuals: The 'Golden Phase'. Photorealistic faces and hands set against flat, ornamental, mosaic-like patterned clothes and backgrounds. Geometric shapes. Color Palette: Dominant Gold Leaf, metallic textures, black, and jewel tones (emerald, ruby). Aesthetic: Decorative, erotic, opulent, divine." },
    dali: { name: "Salvador Dalí", prompt: "Painter Persona: Salvador Dalí. Style: Surrealism, Hyper-Realism. Visuals: Melting objects (clocks, faces), elephants on spindly legs, vast barren landscapes with low horizons. Dream logic. Painted with photographic precision. Color Palette: Warm, arid desert colors (yellow, ochre) contrasted with deep blue sky and long black shadows. Aesthetic: Bizarre, dreamlike, sharp, illogical." }
  },
  custom: {
    semih: { name: "Semih", prompt: "Style: Cinematic Storytelling, Narrative Focus. Visuals: Immersive cinematic shot capturing a story moment. Focus on visual storytelling, emotional context, and dramatic composition. Not just a static image, but a moment in a story." },
    kazim: { name: "Kazım", prompt: "Style: Mystery & Warmth. Visuals: Main character facing AWAY from camera (back view/over-theshoulder). Faces hidden or obscured. Low angle shots to emphasize scale. Color Palette: Warm tones, amber, orange, sunset hues, sepia. Aesthetic: Atmospheric, secretive, imposing." },
    batuhan: { name: "Batuhan", prompt: "Style: Epic VFX, High Action. Visuals: Exaggerated visual effects, heavy environmental particles (swirling dust, flying leaves, embers, debris). Dramatic wind, volumetric fog, magical or sci-fi energy. High impact composition. Aesthetic: Blockbuster movie, intense atmosphere, dynamic." },
    kutay: { name: "Kutay", prompt: "Style: Authentic Turkish Hanafi Islamic Tradition. Visuals: 1) ORIENTATION (CRITICAL): In MOSQUE scenes, camera view is from BEHIND the congregation. People's BACKS are turned to the camera, facing TOWARDS the Mihrab. NEVER show people facing the camera with Mihrab in background. 2) ROWS: Perfectly straight, tight, shoulder-to-shoulder rows (Saf). No gaps. 3) POSTURE: Varied positions allowed (Standing, Bowing, Sajdah). 4) RUG: Rectangular Turkish rugs. Feet positioned STRICTLY at the bottom edge. 5) ATTIRE: Modern Turkish modest fashion. Men in trousers/shirts (no Arab thobes). Women (ONLY IF requested) in full hijab covering ALL hair completely. 6) ENVIRONMENT: Turkish architectural aesthetics. NO Arabic text, NO calligraphy on walls. In HOME scenes, do NOT include a Mihrab. Aesthetic: Spiritual, respectful, realistic." },
    oguzhan: { name: "Oğuzhan", prompt: "Style: Double Exposure, Surreal Overlay. Visuals: Two images blended together. A scene composed INSIDE the silhouette of a large object or a character's profile. Or a full-body character walking inside a close-up of a face. High contrast blending. Aesthetic: Dreamlike, artistic, multi-layered, conceptual." },
    evliya: {
      name: "Evliya",
      prompt: "Director Persona: Evliya. Style: Spiritual Historical Realism, Ottoman/Islamic Aesthetic. Atmosphere: Luminous (Nurani), Serene, Dignified (Vakur). Color Palette: Warm parchment, soft gold, emerald green, pure white light. \n\nCHARACTER INTERPRETATIONS (Strict Adherence):\n- Evliya Çelebi: Young adult, thin build, curious/attentive eyes, 17th-century Ottoman traveler attire/turban. Enthusiastic observer.\n- Sa’d bin Ebi Vakkas: Mature, imposing/strong warrior posture, calm/wise face, Sahaba attire, traditional bow & arrow. Protective leader.\n- Hz. Bilal: Middle-aged, dark skin, dignified/peaceful face, serious expression, Muezzin attire, modest robe.\n- Ibrahim Efendi: Elderly, white beard, wise/calm face, simple Ottoman scholar robe. Dream interpreter vibe.\n- Sheikh Abdullah Dede: Elderly, radiant face (Nurani), compassionate eyes, Sufi Tekke attire.\n- Holy Figures (Prophets/Sahaba): Depicted as silhouettes of light (Noor) or with veiled faces, enveloped in a spiritual glow. Respectful and abstract representation. NO facial features for Prophets.\n- General Atmosphere: Humble, respectful, historical accuracy blended with a spiritual, ethereal glow."
    },
    detayci: {
      name: "Detaycı",
      prompt: "Style: Atmospheric B-Roll, Narrative Details & Unconventional Angles. Visuals: Focus on 'Insert Shots' (Extreme Close-ups of hands signing papers, eyes, objects, textures) OR 'Extreme Wide Shots' (tiny silhouette in vast environment). Use Over-the-Shoulder (OTS) or Amors angles where the main subject is blurred or back-facing. Avoid standard front-facing portraits. Composition: High use of negative space, depth of field (bokeh), macro details. Aesthetic: Cinematic, storytelling through objects and environment rather than faces."
    },
    saadet: {
      name: "Saadet",
      prompt: "Style: Historical Documentary Realism. Visuals: Focus on materiality: raw textures, irregular masonry, 'under construction' states, and imperfections. Emphasis on authentic scale and context regardless of camera angle. Humans are defined by labor/role, faces are visible, natural and detailed (no blurring, no hiding). Composition strictly respects the requested framing and aspect ratio. Atmosphere: Quiet, respectful, objective, warm natural light with long shadows. No dramatization, just pure, calm historical reconstruction."
    }
  }
};

export const STYLES = [
  { id: 'none', name: 'Yok', value: '' },
  { id: 'photo', name: 'Ultra Gerçekçi', value: 'Reinterpret in a photorealistic, 8k, highly detailed, raw photo style' },
  { id: 'oil', name: 'Yağlı Boya', value: 'Reinterpret in the style of an oil painting, textured, classical art, impasto brushstrokes' },
  { id: 'anime', name: 'Anime', value: 'Reinterpret as an anime style, vibrant colors, ultra cell shaded' },
  { id: '3d', name: '3D Render', value: 'Reinterpret as cartton 3d animation style, 3D render, 3D animation' },
  { id: 'pixel', name: 'Pixel Art', value: 'Reinterpret as pixel art, 8-bit, retro game style' },
  { id: 'vector', name: 'Vektör', value: 'Reinterpret as minimalist vector art, flat design' },
  { id: 'grunge', name: 'Grunge', value: 'Reinterpret in a grunge style, light bone color palette, ink bleed effect, watercolor splatter, distressed texture' },
  { id: 'double', name: 'Double Exposure', value: 'Reinterpret as a double exposure, superimposed, dreamlike, multiple layers' },
];
